api_platform:
    title: 'KH-AGENCY-CRM-API'
    description: 'Project for managing content plans'
    version: '0.0.1'

    use_symfony_listeners: true

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
